[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "term-assist"
version = "0.1.0"
authors = [
    { name = "Logan Kirkland", email = "logan@logankirk.land" }
]
maintainers = [
    { name = "Logan Kirkland", email = "logan@logankirk.land" }
]
description = """
A basic CLI wrapper around Anthropic's Claude API to help out with \
terminal issues."""
readme = "README.md"
license = { file = "COPYING" }
dependencies = [
    "anthropic~=0.25.8",
    "PyYAML~=6.0.1"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://sr.ht/~logankirkland/term-assist/"
Repository = "https://git.sr.ht/~logankirkland/term-assist"
"Bug Tracker" = "https://todo.sr.ht/~logankirkland/term-assist"
"Mailing List" = "https://lists.sr.ht/~logankirkland/term-assist"

[project.optional-dependencies]
develop = [
    "build"
]

[project.scripts]
ta = "term_assist.term_assist:main"
