PhenoCams:
  P_GRI_FOR_1:
    aoi: Spruce and pine forest
    backups:
      aurora02_dirpath: /home/aurora02/data/SITES/Spectral/data/catalog/grimso/locations/GRI_FOR/platforms/PhenoCam/P_GRI_FOR_1/
    description:  Mix of hemi-boreal and boreal, spruce and pine forest
    ecosystem_of_interest: FOR
    geolocation:
      point:
          epsg: "epsg:4326"
          latitude_dd: 59.72868
          longitude_dd: 15.47249
    height_in_meters_above_ground: 
    legacy_acronym: GRI-FOR-P01
    location_id: GRI_FOR
    maintainance_log_filepath: '/home/aurora02/data/SITES/Spectral/code/pycode/SSTC/sstc-core/src/sstc_core/sites/spectral/maintainance/Grimso-GRI_FOR_1-mantainance_log.yaml'
    status: Active
    phenocam_rois:
      # ROI is all the image extent
      ROI_01: {'points': [[0, 0], [1024, 0], [1024, 768], [0, 768]],
        'color': [0, 0, 255],
        'thickness': 7}    
    platform_id: P_GRI_FOR_1
    platform_type: PhenoCam    
    sftp_dirpath: /grimso/data/PhenoCam/GRI-FOR-P01/
    station_acronym: GRI
    station_name: Grims√∂
    viewing_direction': 
    metadata:
      'TITLE': ''
      'SITES STATION': ''
      'TIME PERIOD': null
      'TIME RESOLUTION': null
      'TIME ZONE': 'UTC+1'
      'SAMPLING POINT': 'Phenocam 01 :  platform_id=P_GRI_FOR_1'
      'LATITUDE': ''
      'LONGITUDE': ''
      'ALTITUDE': 'm.a.s.l'
      'FILE RETRIEVED FROM': 'https://data.fieldsites.se Link to metadata landing page is available in separate file in the downloaded zip.'
      'DATA POLICY': 'SITES data is licensed under a Creative Commons Attribution 4.0 international license (http://creativecommons.org/licenses/by/4.0/).'
      'PARAMETERS & UNITS': 'Digital Numbers (DN)'
      'DESCRIPTION': 'Collection of quality filtered phenocamera RGB images every half an hour from 10:00 to 14:30 UTC+1.'
      'SENSOR DESCRIPTION': 'Images stored in JPG format.'
      'DATA ACQUISITION': ""
      'PROCESSING METHODS': 
        L1_QFI: 'Data processing Level 1 Quality Filtered Images (QFI) were selected by filtered out manually from the original image collection. Individual flags were used to flag regions of interest (ROIs) that contain haze, shadows, sun glare, rain droplets, fog, or represent low-light, blurry conditions or obstacles in the image regions of interest.'
        L2_RGB_CIMV: 'Data processing level 2 Red Green Blue (RGB) Composite Image Mean Values, daily'
        L2_GCC_CIMV: 'Data processing level 2 Green Chromatic Coordinates  (GCC) Composite Image Mean Values, daily'
        L2_RCC_CIMV: 'Data processing level 2 Red Chromatic Coordinates  (RCC) Composite Image Mean Values, daily' 
        L3_ROI_TS: 'Data processing level 3 Phenocam - Green and Red Chromatic Coordinates time series of the RGB Composite Image of Mean Values - Region of Interest (ROI) Mean and Standard Deviation, daily values with QFLAG values and individual flags assesment per ROI'
      'DATA PRODUCT TYPE': 'L1_QFI'
      'DATA PRODUCT DESCRIPTION': 'Data Processing Level 1 Quality Filtered Images'
       