[project]
name = "multillm"
version = "0.1021"
authors = [
  { name="VerifAI Inc", email="hello@verifai.ai" },
]

description = "VerifAI MultiLLM: A module to invoke multiple LLMs concurrently and rank their results"
readme = "README.md"
requires-python = ">=3.8"

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
[project.scripts]
multillm = "multillm.example:main"

[project.urls]
"Homepage" = "https://github.com/verifai/multiLLM"
"Bug Tracker" = "https://github.com/verifai/multiLLM"

[build-system]
requires = ["setuptools","transformers", "redis", "openai", "vertexai", "google-cloud-aiplatform","anthropic"]


[optional-dependencies]
transformers = "*"
redis = "*"
openai = "*"
vertexai = "*"
google-cloud-aiplatform = "*"

[tool.poetry.dependencies]
transformers = "*"
redis = "*"
openai = "*"
vertexai = "*"
google-cloud-aiplatform = "*"
