[tool.poetry]
name = "xnano"
version = "0.0.29"
description = ""
authors = ["Hammad Saeed <hvmmad@gmail.com>"]
license = "MIT"
readme = "README.md"


[tool.poetry.dependencies]
python = "^3.11"
loguru = "^0.7.1"
rich = "^13.9.2"
# llms // serialization
instructor = "^1.5.2"
jsonpatch = "^1.33"
# data
semchunk = "^2.2.0"
pypdf2 = "^3.0.1"
python-docx = "^1.1.2"
openpyxl = "^3.1.5"
# all
chromadb = "^0.5.13"
litellm = "^1.49.2"


[tool.poetry.extras]
all = ["chromadb", "litellm"]


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"
ipython = "^8.28.0"
poetry = "^1.8.3"
ruff = "^0.6.9"
uv = "^0.4.20"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.pyright]
venvPath = "."
venv = ".venv"
