
[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "quao"
version = "0.4.12.1a"
description = "Quao Library supporting Quao Platform for Quantum Computing"
readme = "README.md"
authors = [{ name = "CITYNOW Co. Ltd. ", email = "corp@citynow.vn" }]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = ["quao", "quantum"]
dependencies = [
    "qiskit==0.44.1",
    "qiskit-aer-gpu==0.11.2",
    "qbraid==0.4.5",
    "amazon-braket-sdk==1.49.1",
    "qiskit-ibm-runtime~=0.11.2",
    "qiskit-ibm-provider~=0.6.2",
    "matplotlib",
    "pylatexenc",
    "loguru",
    "tytan~=0.0.17",
    "pyqubo~=1.4.0",
    "dwave-samplers~=1.2.0",
    "dwave-ocean-sdk~=6.4.1"
]
requires-python = ">=3.7"

[project.optional-dependencies]
dev = ["black", "bumpver", "isort", "pip-tools", "pytest"]

[project.urls]
Homepage = "https://citynow.vn/"
