[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "ogbench"
version = "0.1.0-alpha.1"
requires-python = ">=3.8"
dependencies = [
    "mujoco >= 3.1.6",
    "dm_control >= 1.0.20",
    "gymnasium[mujoco]",
]
authors = [
    { name = "Seohong Park", email = "seohong@berkeley.edu" },
    { name = "Kevin Frans" },
    { name = "Benjamin Eysenbach" },
    { name = "Sergey Levine" },
]
maintainers = [
    { name = "Seohong Park", email = "seohong@berkeley.edu" }
]
readme = "README.md"
license = { file = "LICENSE" }
classifiers = ["License :: OSI Approved :: MIT License"]
dynamic = ["description"]

[project.optional-dependencies]
train = [
]
dev = [
    "ruff",
]
all = [
    "ogbench[train,dev]",
]

[project.urls]
Home = "https://github.com/seohongpark/ogbench"

[tool.ruff]
target-version = "py310"
line-length = 120

[tool.ruff.format]
quote-style = "single"
