[project]
name = "md2bbcode"
description = "Convert Markdown to BBCode using a custom Mistune renderer."
readme = "README.md"
license = "GPL-3.0-or-later"
dynamic = ["version"]
authors = [
  { name = "Redbot", email = "ask@redguides.com" }
]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
  "Operating System :: OS Independent",
  "Development Status :: 5 - Production/Stable",
  "Intended Audience :: Developers",
  "Topic :: Text Processing :: Markup :: HTML",
  "Topic :: Utilities",
  "Topic :: Text Processing :: Markup :: Markdown"
]
dependencies = [
  "mistune>=3.0.2",
  "beautifulsoup4"
]

[project.scripts]
md2bbcode = "md2bbcode.main:main"
md2ast = "md2bbcode.md2ast:main"
html2bbcode = "md2bbcode.html2bbcode:main"

[project.urls]
Homepage = "https://github.com/RedGuides/md2bbcode"
Repository = "https://github.com/RedGuides/md2bbcode.git"
Issues = "https://github.com/RedGuides/md2bbcode/issues"
Documentation = "https://github.com/RedGuides/md2bbcode#readme"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "src/md2bbcode/__about__.py"

[tool.hatch.build.targets.sdist]
include = [
  "README.md",
  "LICENSE",
  "src/md2bbcode/*.py",
  "src/md2bbcode/renderers/*.py",
  "bb_codes.xml"
]
exclude = ["__pycache__/**"]

[tool.hatch.build.targets.wheel]
include = [
  "README.md",
  "LICENSE",
  "src/md2bbcode/*.py",
  "src/md2bbcode/renderers/*.py",
  "bb_codes.xml"
]
exclude = ["__pycache__/**"]
packages = ["src/md2bbcode"]

[tool.hatch.envs.default]
dependencies = [
  "mistune>=3.0.2",
  "beautifulsoup4"
]
