[project]
name = "aftonfalk"
version = "0.1.3"
authors = [
  { name="Erik Bremstedt", email="erik.bremstedt@gmail.com" },
]
description = "Create runs for data pipelines"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "pendulum==3.0.0",
    "pyodbc==5.1.0"
]

[project.urls]
Homepage = "https://github.com/pypa/sampleproject"
Issues = "https://github.com/pypa/sampleproject/issues"
