[tool.poetry]
name = "decentriq_util"
version = "0.1.0-dev13"
description = "Utility functions for Python code run in Decentriq workers"
authors = ["hafenr <robin.hafen@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
protobuf = "^4.21"
pandas = "^2.1.1"
pyspark = "^3.5.0"
psutil = "^5.9.6"
pyarrow = "^14.0.0"
numpy = "^1.26.1"

[tool.poetry.dev-dependencies]
pytest = "^7.2.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
