[build-system]
requires = ["poetry-core==1.9.1"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "ripley"
version = "0.dev133"
description = "data / database manipulation tool. See: https://gitlab.com/d-ganchar/ripley/-/pipelines/1498198176/"
authors = ["Danila Ganchar"]
license = "MIT"
readme = "README.md"
keywords = ['data', 'database', 'sql', 'clickhouse']

classifiers = [
    'Development Status :: 3 - Alpha',
    'Topic :: Database',
    'Programming Language :: SQL',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
    'Programming Language :: Python :: 3.12',
]

[tool.poetry.dependencies]
python = ">=3.8 <3.13"


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.3"
parameterized = "^0.9.0"
ruff = "0.5.1"
clickhouse-driver = "0.2.8"
build = "1.2.2"
pytest-html = "^4.1.1"
pytest-cov = "^5.0.0"
junitxml = "^0.7"
