[tool.poetry]
name = "fluidattacks-core"
version = "1.3.4"
description = "Fluid Attacks Core Library"
authors = ["Development <development@fluidattacks.com>"]
license = "MPL-2.0"
readme = "README.md"
classifiers = [
    "Development Status :: 1 - Planning",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Mozilla Public License 2.0 (MPL 2.0)",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Topic :: Software Development :: Libraries",
]

[tool.poetry.dependencies]
python = "^3.11"
freezegun = ">=1.4"
pytest-cov = ">=4.1"
pytest-asyncio = ">=0.21"
pytest = ">=7.4"
moto = { extras = ["server"] , version = "^5.0" }
boto3 = ">=1.34"
aioboto3 = ">=13.1"
cvss = "3.0"
coverage = ">=7.4"

[tool.poetry.group.dev.dependencies]
boto3-stubs = { extras = ["essential", "dynamodbstreams"], version = ">=1.34" }
types-aioboto3 = { extras = ["bedrock-runtime", "marketplace-entitlement", "meteringmarketplace"], version = ">=13.1" }
types-aiobotocore = { extras = ["dynamodb"], version = ">=2.15" }

[tool.poetry.scripts]
fluidattacks-core-test = "fluidattacks_core.testing.cli:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
