---
# PreTasks:
# - name: "Restart runtime"
#   command: "./nu_scripts/start_rt.sh"

# PostTasks:
# - name: "Shutdown runtime"
#   command: "./nu_scripts/stop_rt.sh"
Framework: Nu

PrerunGdbCommands:
- name: "enable script"
  command: "source ../gdb_ext/runtime-gdb.py"
# - name: "enable non-stop mode"
#   command: "set non-stop off"

ServiceDiscovery:
  Broker:
    hostname: 10.10.2.1
    port: 10101
