[tool.poetry]
name = "qatiumsdk"
version = "0.0.1"
description = "SDK to build Qatium plugins in Python"
authors = ["Qatium Product Team"]
readme = "README.md"
packages = [{include = "qatiumsdk"}]

[tool.poetry.dependencies]
python = "^3.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"