[project]
name = "mm-solana"
version = "0.1.5"
description = ""
requires-python = ">=3.12"
dependencies = [
    "mm-std~=0.1.4",
    "solana~=0.34.0",
    "base58~=2.1.1",
    "Jinja2~=3.1.3",
    "PyYAML~=6.0",
    "typer~=0.12.5",
    "httpx-socks~=0.9.1",
]
[project.scripts]
mm-solana = "mm_solana.cli.cli:app"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
dev-dependencies = [
    "pytest~=8.3.3",
    "pytest-xdist~=3.6.1",
    "pytest-httpserver~=1.1.0",
    "coverage~=7.6.3",
    "ruff~=0.6.9",
    "pip-audit~=2.7.0",
    "bandit~=1.7.10",
    "mypy~=1.12.0",
    "types-python-dateutil~=2.9.0.20241003",
    "types-PyYAML~=6.0.12.20240917",
]

[tool.mypy]
python_version = "3.12"
mypy_path = "stubs"
warn_no_return = false
implicit_reexport = true
strict = true
exclude = ["^tests/", "^tmp/"]
[[tool.mypy.overrides]]
module = ["pydash", "click_aliases", "httpx_socks"]
ignore_missing_imports = true


[tool.ruff]
line-length = 130
target-version = "py312"
lint.select = [
    "F", # Pyflakes
    "E", "W", # pycodestyle
    "UP", # pyupgrade
    "B", # flake8-bugbear
    "A", # flake8-builtins
    "COM", # flake8-commas
    "C40", # flake8-comprehensions
    "G", # flake8-logging-format
    "PIE", # flake8-pie
    "T20", # flake8-print
    "RUF", # Ruff-specific rules
]
lint.ignore = [
    "A003", # builtin-attribute-shadowing
    "B008", # function-call-argument-default
    "COM812",
    "UP040", # non-pep695-type-alias
]


[tool.bandit]
exclude_dirs = ["tests"]
skips = ["B311"]
