[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "scVital"
version = "0.0.3.3"
authors = [
  { name="Jonathan Rub", email="jor4008@med.cornell.edu" },
]
description = "Deep Learning ALrogithm for integration of scRNA-seq data"
readme = "README.md"
requires-python = ">=3.8"
license = { file = "LICENSE" }
classifiers = [
    "Programming Language :: Python :: 3",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
]
dependencies = [
    "numpy",
    "pandas",
    "scanpy",
    "torch"
]

[project.urls]
Homepage = "https://github.com/j-rub/scVital"

[tool.setuptools.packages.find]
where = ["src"]

