[project]
name = "funbuild"
version = "1.5.13"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [ "gitpython>=3.1.43", "ruff>=0.6.9", "toml>=0.10.2", "uv>=0.4.21",]

[project.scripts]
funbuild = "funbuild.core:funbuild"
