[tool.poetry]
name = "hvi-wrap"
version = "0.3.4"
description = ""
authors = ["Guy McBride <guy_mcbride@keysight.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^2.1.2"
black = "^24.10.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
