[build-system]
requires = ["hatchling", "hatch-vcs", "hatch-fancy-pypi-readme"]
build-backend = "hatchling.build"

[project]
name = "cdef_cohort_generation"
dynamic = ["version", "readme", "urls"]
description = "Add your description here"
authors = [
    { name = "Tobias Kragholm", email = "50784887+tkragholm@users.noreply.github.com" },
]
dependencies = [
    "polars[all]>=1.9.0",
    "rich>=13.9.2",
    "pydantic[mypy]>=2.9.2",
    "pydantic-settings>=2.5.2",
]
requires-python = ">= 3.12"
license = "MIT"

[project.scripts]
cdef-cohort-generation = "cdef_cohort_generation.main:main"

[tool.hatch.version]
source = "vcs"

[tool.hatch.metadata.hooks.fancy-pypi-readme]
content-type = "text/markdown"

[[tool.hatch.metadata.hooks.fancy-pypi-readme.fragments]]
path = "README.md"

[[tool.hatch.metadata.hooks.fancy-pypi-readme.substitutions]]
pattern = '\[!(NOTE|TIP|IMPORTANT|WARNING|CAUTION)\]'
replacement = '**\1**:'

[tool.hatch.metadata.hooks.vcs]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/cdef_cohort_generation"]

[tool.hatch.build.targets.wheel.force-include]
"mappings" = "mappings"
".env.example" = ".env.example"

[tool.rye]
universal = true
managed = true
dev-dependencies = [
    "mypy>=1.11.2",
    "pytest>=8.3.3",
    "hatch-vcs",
    "hatch-fancy-pypi-readme",
]

[tool.rye.scripts]
test = "pytest tests/"
static = "mypy --strict src/"

[tool.ruff]
line-length = 100
target-version = "py312"
fix = true

[tool.ruff.lint]
select = ["E", "B", "F", "UP", "I001", "T203"]

[tool.mypy]
plugins = ["pydantic.mypy"]
strict = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_decorators = true
disallow_any_generics = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unreachable = true
warn_unused_ignores = true
strict_equality = true
warn_return_any = true
check_untyped_defs = true

[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true
warn_untyped_fields = true
