[tool.poetry]
name = "i38e-utils"
version = "1.0.46"
description = "Utilities for IBIS applications in data science and engineering"
authors = ["Luis Valverde <lvalverdeb@gmail.com>"]
readme = "README.md"
packages = [{include = "i38e_utils"}]

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
pandas = "^2.1.4"
django = "4.1.13"
# django="5.0.3"
openpyxl = "^3.1.2"
pydantic = "^2.6.4"
tomli = "^2.0.1"
geopy = "^2.4.1"
dask = {extras = ["complete"], version = "^2024.3.0"}
tqdm = "^4.66.5"
folium = "^0.17.0"
osmnx = "^1.9.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
